version: '3.1'
services:

  nginx:
    image: nginx:stable
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/40-user-app.sh:/docker-entrypoint.d/40-user-app.sh
    ports:
      - 55000:80
    privileged: false

  php:
    build: ./docker/php/
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    entrypoint: /docker-entrypoint.sh
    command: "/usr/sbin/php-fpm8.1 -O"
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      LOG_CHANNEL: stderr
      REDIS_HOST: redis
      INTERNAL_API_SIG: BpmjhgMuI9kwcq
      QUEUE_CONNECTION: redis
      BROADCAST_DRIVER: pusher
      PUSHER_HOST: soketi
      PUSHER_PORT: 8084
      PUSHER_APP_ID: "ytlive0268"
      PUSHER_APP_KEY: "Hf9ELp7X6AHaPJ"
      PUSHER_APP_SECRET: "YIf912xR62gCZ6SngM5u1Vc12EP2"
    volumes:
      - .:/app
      - ./docker/php/php.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - ./docker/php/pool.conf:/etc/php/8.1/fpm/pool.d/z-overrides.conf
      - ./docker/php/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./docker/php/entrypoint:/docker-entrypoint.d
      - ./docker/php/bash_aliases:/home/app/.bash_aliases
    privileged: false
  
  db:
    image: percona/percona-server:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 33063:3306
    volumes:
      - yt-gaming-db:/var/lib/mysql
    privileged: false
  
  redis:
    image: redis:alpine
    restart: unless-stopped
    privileged: false
  
  frontend:
    build: ./frontend/
    restart: unless-stopped
    volumes:
      - .:/app
      - ./frontend/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./frontend/entrypoint:/docker-entrypoint.d
    privileged: false
  
  soketi:
    build: ./docker/soketi/
    restart: unless-stopped
    environment:
      PUSHER_HOST: soketi
      PUSHER_PORT: 8084
      PUSHER_APP_ID: "ytlive0268"
      PUSHER_APP_KEY: "Hf9ELp7X6AHaPJ"
      PUSHER_APP_SECRET: "YIf912xR62gCZ6SngM5u1Vc12EP2"
    volumes:
      - ./docker/soketi/ecosystem.config.js:/app/ecosystem.config.js
    ports:
      - 8084:8084
      - 9601:9601
    privileged: false
  
  crawler:
    build: ./docker/crawler/
    restart: unless-stopped
    volumes:
      - ./crawler:/app
      - ./docker/crawler/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./docker/crawler/entrypoint:/docker-entrypoint.d
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      APP_URL: http://nginx
      INTERNAL_API_SIG: BpmjhgMuI9kwcq
    privileged: false

volumes:
  yt-gaming-db:

# networks:
#   default:
#     name: dc
#     external: true
