version: '3.1'
services:
  redis:
    image: 'redis:alpine'
    restart: unless-stopped

  nginx:
    image: 'nginx:alpine'
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '55000:80'

  php:
    build: ./
    working_dir: /app
    restart: unless-stopped
    entrypoint: /docker-entrypoint.sh
    command: "/usr/sbin/php-fpm8.1 -O"
    volumes:
      - '.:/app'
      - './docker/php/php.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
      - './docker/php/pool.conf:/etc/php/8.1/fpm/pool.d/z-overrides.conf'
      - './docker/php/docker-entrypoint.sh:/docker-entrypoint.sh'
      - './docker/php/entrypoint:/docker-entrypoint.d'
