version: '3.1'
services:

  nginx:
    image: 'nginx:stable'
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf'
      - './docker/nginx/40-user-app.sh:/docker-entrypoint.d/40-user-app.sh'
    ports:
      - '55000:80'

  php:
    build: ./docker/php/
    working_dir: /app
    restart: unless-stopped
    entrypoint: /docker-entrypoint.sh
    command: "/usr/sbin/php-fpm8.1 -O"
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    volumes:
      - '.:/app'
      - './docker/php/php.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
      - './docker/php/pool.conf:/etc/php/8.1/fpm/pool.d/z-overrides.conf'
      - './docker/php/docker-entrypoint.sh:/docker-entrypoint.sh'
      - './docker/php/entrypoint:/docker-entrypoint.d'
  
  db:
    image: percona/percona-server:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306"
    volumes:
      - /var/lib/mysql
  
  redis:
    image: 'redis:alpine'
    restart: unless-stopped
  
  frontend:
    build: ./frontend/
    restart: unless-stopped
    volumes:
      - '.:/app'
      - './frontend/docker-entrypoint.sh:/docker-entrypoint.sh'
      - './frontend/entrypoint:/docker-entrypoint.d'
  
  soketi:
    build: ./docker/soketi/
    restart: unless-stopped
    volumes:
      - './docker/soketi/ecosystem.config.js:/app/ecosystem.config.js'
    ports:
      - '8084:8084'
      - '9601:9601'
  
  crawler:
    build: ./crawler/
    restart: unless-stopped
    volumes:
      - '.:/app'
      - './crawler/docker-entrypoint.sh:/docker-entrypoint.sh'
      - './crawler/entrypoint:/docker-entrypoint.d'
